trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  yelpimage: 'ghcr.io/larryclaman/dockerdetectsecrets:latest'
  pluginsdir: yelp-plugins



steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
- script: |
    #pip install wheel
    pip install detect-secrets
  displayName: Install detect-secrets


- script: |
    # pipeline doesn't detect output, so have tool save output to file & cat it.
    touch $(Build.StagingDirectory)/creds.json
    detect-secrets scan --custom-plugins yelp-plugins/azure_storage_key.py > $(Build.StagingDirectory)/creds.json # pipeline doesn't 
    cat $(Build.StagingDirectory)/creds.json
  displayName: 'detect-secrets credentials scan'