trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  yelpimage: 'ghcr.io/larryclaman/dockerdetectsecrets:latest'
  pluginsdir: yelp-plugins
  pythonappdir: /home/vsts/.local/bin


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
- script: |
    #pip install wheel
    pip install detect-secrets -v
  displayName: Install detect-secrets


- script: |
    $(pythonappdir)/detect-secrets scan --custom-plugins yelp-plugins/
    #$(pythonappdir)/detect-secrets scan --custom-plugins https://raw.githubusercontent.com/Yelp/detect-secrets/pre-v1-launch/detect_secrets/plugins/azure_storage_key.py > .secrets.baseline
    #$(pythonappdir)/detect-secrets audit .secrets.baseline
  displayName: 'detect-secrets credentials scan'