trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  yelpimage: 'ghcr.io/larryclaman/dockerdetectsecrets:latest'
  pluginsdir: yelp-plugins


steps:
- task: CmdLine@2
  inputs:
    script: |
      pip install detect-secrets
      detect-secrets scan --custom-plugins $(pluginsdir)